name: 'Release Build'
on:
  push:
    tags:
      - 'v*'
jobs:
  Build:
    name: Build TSC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: var
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        id: build_tsc
        run: npm run build
        with:
          releaseDirectory: lib

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: nest-shared-${{ steps.var.outputs.tag }}
          path: lib

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.var.outputs.tag }}
          release_name: ${{ steps.var.outputs.tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false